resize_shape: [256, 256]
targets: ['hot_dog']
model_file_paths: ["hotdog_cnn_classifier_params.h5", "hotdog_cnn_classifier_layers.json"]
base_model_url: "https://github.com/RogueNPC/Is-Hotdog/releases/download/v1.0"
model_sha256: ""
